
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    app: bgg
  namespace: bggns
spec:
  type: LoadBalancer
  ports:
  - port: 8080 
    targetPort: 3000   
  selector:
    app: bgg-app
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    app: bgg
    owner: senaka
  namespace: bggns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgg-app
  template:
    metadata:
      labels:
        app: bgg-app
    spec:
      containers:
      - image: stackupiss/bgg-backend:v1
        name: bgg-app      
        ports:
        - containerPort: 3000          
        env:
          - name: BGG_DB_USER
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: bgg_db_user
          - name: BGG_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: bgg_db_host   
          - name: BGG_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbsecret
                key: bgg_db_password  

  