apiVersion: v1
kind: ConfigMap
metadata:
  name: dbconfig
  labels:
   name: dbconfig
   tier: DB
  namespace: bggns 
data:
   bgg_db_user: root
   bgg_db_host: bggdb.bggns.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
  labels:
   name: dbconfig
   tier: DB
  namespace: bggns
data:
   bgg_db_password: Y2hhbmdlaXQ=