
apiVersion: v1
kind: Service
metadata:
  name: bggdb
  namespace: bggns
spec:
  type: ClusterIP
  ports:
  - port: 3306 
    targetPort: 3306   
  selector:
    app: bggdb
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-pod
  labels:
    app: bgg-database
    owner: senaka
  namespace: bggns
spec:
  selector:
    matchLabels:
      app: bggdb
  template:
    metadata:
      labels:
        app: bggdb
    spec:
      containers:
      - image: stackupiss/bgg-database:v1
        name: bggdb        
        ports:
        - containerPort: 3306
          name: mysql
        
          
  