apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./wordpress-db.yaml
  - ./wordpress-app.yaml
  - ./wordpress-ing.yaml
  
secretGenerator:
- name: mysql-pass
  literals:
  - password=p@ssw0rd

namespace: wpns 