#apiVersion: v1
#kind: Service
#metadata:
#  name: wordpress-mysql
#  labels:
#    app: wordpress
#spec:
#  ports:
#    - port: 3306
#  selector:
#    app: wordpress
#    tier: mysql
#  clusterIP: None
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mysql-pv-claim
#  labels:
#    app: wordpress
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
   name: wp-cluster
   labels:
      name: wp-cluster
spec:
   replicas: 2
   secretName: wp-dbsecret
   #persistentVolumeClaim:
   #   accessModes:
   #   - ReadWriteOnce
   #   storageClassName: do-block-storage 
   #   resources:
   #      requests:
   #         storage: 1Gi

---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlDatabase
metadata:
   name: wpdb-db
   labels:
      name: wpdb-db
spec:
   database: wpdb
   clusterRef:
      name: wpdb-cluster

    
