---
apiVersion: v1
kind: Secret
metadata:
   name: wp-dbsecret
   labels:
      name: wp-dbsecret
data:   
   ROOT_PASSWORD: cm9vdA==
   WORDPRESS_DB_PASSWORD: cm9vdGRi

---
apiVersion: v1
kind: ConfigMap
metadata:
   name: wp-cm
   labels:
      name: wp-cm
data:
   WORDPRESS_DB_HOST: wp-cluster-mysql-master
   WORDPRESS_DB_USER: root
   WORDPRESS_DB_NAME: wpdb